automating last remote ini phases

diff --git a/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system b/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
--- a/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
+++ b/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
@@ -114,6 +114,15 @@ aptitude clean
 # >>> log end#{{{
 echo "${0} done - $(e__datetime_sec)" >> ${ec1_script_log}
 e__datetime_sec > ${ec1_script_log}.done
+
+ec1_ini_phase_system_done_file="${ec1_root_ini_logsdir}/ec1.ini.system.done.ering"
+echo 'ready' > ${ec1_ini_phase_system_done_file}
+if [[ ! -f ${ec1_ini_phase_system_done_file} ]]
+then
+    echo "ERROR: can't access ec1_ini_phase_system_done_file ${ec1_ini_phase_system_done_file}." 2>&1
+    exit 1
+fi
+
 #}}}
 
 #UNSURE: sleeping to provide enough time for reboot execution (it seems that subsequent commands called after the execution of this script begin before effective reboot)
