unsmart_debugging

diff --git a/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system b/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
--- a/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
+++ b/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
@@ -32,6 +32,8 @@ then
     exit 1
 fi
 echo "${0} start - $(e__datetime_sec)" > ${ec1_script_log}
+echo "DEBUG: ec1_user_inidir = ${ec1_user_inidir}" >> ${ec1_script_log}
+echo "DEBUG: ec1_script_log = ${ec1_script_log}" >> ${ec1_script_log}
 if [[ ! -f ${ec1_script_log} ]]
 then
     echo "ERROR: can't write log file ${ec1_script_log} (from script ${0})" 2>&1
@@ -66,7 +68,13 @@ do
     git clone git://github.com/epiculture/${repository}.git
 done
 
-rsync -avh --no-o --no-g --stats ${ec1_system_basedir}/ec1_supervision_templates/ub10.04_x86_64/mu/system_variation_01/ ${ec1_system_ms_basedir}/
+if [[ ! -d ${ec1_system_basedir}/ec1_supervision_templates/ub10.04_x86_64/ms/system_variation_01 ]]
+then
+    echo "ERROR: can't access directory ${ec1_system_basedir}/ec1_supervision_templates/ub10.04_x86_64/ms/system_variation_01" 2>&1
+    exit 1
+fi
+
+rsync -avh --no-o --no-g --stats ${ec1_system_basedir}/ec1_supervision_templates/ub10.04_x86_64/ms/system_variation_01/ ${ec1_system_ms_basedir}/
 rm -R ${ec1_system_basedir}/ec1_supervision_templates
 
 #network
