live test, refactoring & debugging

diff --git a/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system b/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
--- a/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
+++ b/ub10.04_x86_64/ms/system_variation_01/00ini/ec1_install_system
@@ -14,7 +14,7 @@ date +%Y-%m-%d_%H%M%S
 ec1_system_basedir="/.ec1"
 ec1_system_ms_basedir="${ec1_system_basedir}/00ms"
 ec1_system_ms_data_dir="${ec1_system_basedir}/00ms/00data"
-ec1_user_inidir="${HOME}/.ec1.ini"
+ec1_user_inidir="$(dirname ${0})"
 ec1_user_ini_logsdir="${ec1_user_inidir}/logs"
 
 ec1_script_log="${ec1_user_ini_logsdir}/ec1.ini.system"
@@ -32,6 +32,11 @@ then
     exit 1
 fi
 echo "${0} start - $(e__datetime_sec)" > ${ec1_script_log}
+if [[ ! -f ${ec1_script_log} ]]
+then
+    echo "ERROR: can't write log file ${ec1_script_log} (from script ${0})" 2>&1
+    exit 1
+fi
 #}}}
 
 umask 027
@@ -66,7 +71,8 @@ rm -R ${ec1_system_basedir}/ec1_supervision_templates
 mv ${ec1_user_inidir}/dispatch/system/00data ${ec1_system_ms_basedir}/
 
 ec1_data_system_files=(
-	${ec1_system_ms_data_dir}/hostname
+	${ec1_system_ms_data_dir}/entity.domain
+	${ec1_system_ms_data_dir}/machine.hostname
 	${ec1_system_ms_data_dir}/machine.ssh_port
 	)
 for ec1_data_system_file in ${ec1_data_system_files[@]}
@@ -77,42 +83,41 @@ do
 	exit 1
     fi
 done
+ec1_system_machine_hostname=$(cat "${ec1_system_ms_data_dir}/machine.hostname")
+ec1_system_entity_domain=$(cat "${ec1_system_ms_data_dir}/entity.domain")
+ec1_system_machine_fqdn="${ec1_system_machine_hostname}.${ec1_system_entity_domain}"
+cp -p /etc/hostname ${ec1_system_ms_data_dir}/etc_hostname_00ori
+cat "${ec1_system_machine_fqdn}" > /etc/hostname
 
-cp -p /etc/hostname ${ec1_system_ms_data_dir}/hostname_00ori
-cat "${ec1_system_ms_data_dir}/hostname" > /etc/hostname
-
+#network
 cp /etc/network/interfaces ${ec1_system_ms_basedir}/network/00livelinks/interfaces/interfaces_00ori
 mv /etc/network/interfaces ${ec1_system_ms_basedir}/network/00livelinks/interfaces/
 ln -s ${ec1_system_ms_basedir}/network/00livelinks/interfaces/interfaces /etc/network/
 
+#bash
+mv /etc/login.defs ${ec1_system_ms_basedir}/bash/00livelinks/etc_login.defs/login.defs_00ori
+ln -s ${ec1_system_ms_basedir}/bash/00livelinks/etc_login.defs/login.defs /etc/
 
+#TODO: check file and folder creation umask, may need to activate common-session following operations
+#mv /etc/pam.d/common-session ${ec1_system_ms_basedir}/pam/00livelinks/etc_common-session/common-session_00ori
+#ln -s ${ec1_system_ms_basedir}/pam/00livelinks/etc_common-session/common-session /etc/pam.d/
 
-
-
-
-
-
-
-
-
-#WARNING: linking login.refs !!!!!!!!! might be able to alleviate the need of common-session
-mv /etc/pam.d/common-session ${ec1_system_ms_basedir}/pam/00livelinks/etc_common-session/common-session_00ori
-ln -s ${ec1_system_ms_basedir}/pam/00livelinks/etc_common-session/common-session /etc/pam.d/
-
+#apt
 mv /etc/apt/sources.list ${ec1_system_ms_basedir}/apt/00livelinks/sources.list/sources.list_00ori
 ln -s ${ec1_system_ms_basedir}/apt/00livelinks/sources.list/sources.list /etc/apt/
 
+#mount
 mv /etc/fstab ${ec1_system_ms_basedir}/mount/00livelinks/fstab/
 ln -s ${ec1_system_ms_basedir}/mount/00livelinks/fstab/fstab /etc/
 
+#rvm
 ln -s ${ec1_system_ms_basedir}/rvm/00livelinks/etc_rvmrc/rvmrc /etc/
 
 DEBIAN_FRONTEND=noninteractive aptitude update; aptitude full-upgrade -y
-
 aptitude install debconf-utils -y
 echo "dash dash/sh boolean false"| debconf-set-selections; dpkg-reconfigure -f noninteractive dash
-echo 'postfix postfix/main_mailer_type        select  Internet Site' | debconf-set-selections
-echo 'postfix postfix/mailname        string  dummy.3eclipses.com' | debconf-set-selections
+echo "postfix postfix/main_mailer_type        select  Internet Site" | debconf-set-selections
+echo "postfix postfix/mailname        string  ${ec1_system_machine_fqdn}" | debconf-set-selections
 aptitude install ntp sshfs shorewall mc tar gzip lzma rar unrar bzip2 arj lha rpm unace zip unzip p7zip vim clamav ncdu htop ttf-ubuntu-font-family ttf-droid ttf-liberation screen postfix mailutils -y
 aptitude clean
 
