checking files access

diff --git a/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system b/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system
--- a/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system
+++ b/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system
@@ -42,6 +42,14 @@ do
     git clone git://github.com/epiculture/${repository}.git
 done
 
+if [[ ! -f ${ec1_user_inidir}/00data/hostname.ini ]]
+then
+    echo "ERROR: can't access hostname.ini file: ${ec1_user_inidir}/00data/hostname.ini"
+    exit 1
+fi
+cp -p /etc/hostname ${ec1_user_inidir}/00data/hostname_00ori
+cat "${ec1_user_inidir}/00data/hostname.ini" > /etc/hostname
+
 rsync -avh --no-o --no-g --stats ${ec1_system_basedir}/ec1_supervision_templates/ub10.04_x86_64/mu/system_variation_01/ ${ec1_system_basedir}/00mu/
 
 rm -R ${ec1_system_basedir}/ec1_supervision_templates
