HOME variable not available when launching ering_sl01 from rc.local

diff --git a/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system b/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system
--- a/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system
+++ b/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system
@@ -5,7 +5,15 @@ umask 027
 ufw allow 22/tcp
 ufw --force enable
 
-ec1_user_inidir="${HOME}/.ec1.ini"
+if [[ -z ${EC1__USER_HOME} ]]
+then
+    echo "ERROR: EC1__USER_HOME (${EC1__USER_HOME}) variable must be provided"
+    exit 1
+fi
+
+ec1_user_home=${EC1__USER_HOME}
+ec1_user_inidir="${ec1_user_home}/.ec1.ini"
+
 
 date > ${ec1_user_inidir}/logs/ec1.ini.system.0
 
